#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(HIGH_JUMP_KICK) \
    F(DRAGON_CLAW) \
    F(WATER_PULSE) \
    F(CALM_MIND) \
    F(ROAR) \
    F(TOXIC) \
    F(SNARL) \
    F(BULK_UP) \
    F(TRAILBLAZE) \
    F(ROOST) \
    F(SUNNY_DAY) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(AGILITY) \
    F(ALLY_SWITCH) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(RAIN_DANCE) \
    F(GIGA_DRAIN) \
    F(SNOWSCAPE) \
    F(HAZE) \
    F(GUIDING_STAR) \
    F(THUNDERBOLT) \
    F(SOAK) \
    F(GYRO_BALL) \
    F(CURSE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(PURE_MOON) \
    F(REFLECT) \
    F(CHARGE_BEAM) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(SANDSTORM) \
    F(GRAVITY) \
    F(GRASS_KNOT) \
    F(AERIAL_ACE) \
    F(FLING) \
    F(FACADE) \
    F(REVERSAL) \
    F(REST) \
    F(ENDURE) \
    F(ELECTRIC_TERRAIN) \
    F(ENERGY_BALL) \
    F(SKILL_SWAP) \
    F(SNATCH) \
    F(FLASH) \
    F(MISTY_TERRAIN) \
    F(EERIE_SPELL) \
    F(FLY) \
    F(EARTHQUAKE) \
    F(FOLLOW_ME) \
    F(THUNDER_WAVE) \
    F(FIRE_SPIN) \
    F(GRASSY_TERRAIN) \
    F(BREAKING_SWIPE) \
    F(ALLURING_VOICE) \
    F(FROST_BREATH) \
    F(INCINERATE) \
    F(AURA_SPHERE) \
    F(PSYCHIC_TERRAIN) \
    F(FLASH_FREEZE) \
    F(EERIE_NOISE) \
    F(HONE_CLAWS) \
    F(LEECH_LIFE) \
    F(SLEEP_TALK) \
    F(CUT) \
    F(DAZZLING_GLEAM) \
    F(TRICK) \
    F(SURF) \
    F(SUBSTITUTE) \
    F(VENOSHOCK) \
    F(KNOCK_OFF) \
    F(SWORDS_DANCE) \
    F(SIGNAL_BEAM) \
    F(LOW_SWEEP) \
    F(WORK_UP) \
    F(ROCK_CLIMB) \
    F(DRILL_RUN) \
    F(EXPLOSION) \
    F(BUG_BITE) \
    F(DUAL_WINGBEAT) \
    F(SMACK_DOWN) \
    F(POISON_TAIL) \
    F(STRENGTH) \
    F(METAL_CLAW) \
    F(STRUGGLE_BUG) \
    F(HEADBUTT) \
    F(IRON_TAIL) \
    F(ROCK_SLIDE) \
    F(ROCK_SMASH) \
    F(RAPID_SPIN) \
    F(WEATHER_BALL) \
    F(TERRAIN_PULSE) \
    F(WILL_O_WISP) \
    F(SWIFT) \
    F(INFESTATION) \

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
