gText_Intro_AmIDreaming::
	.string "(…)\p"
	.string "(Where…)\n"
	.string "(Am I…?)\p"
	.string "(… … …)\p"
	.string "(Ah, right…)\n"
	.string "(This dream again.)\p"
	.string "(It always starts out like this…)\p"
	.string "(I'm looking at myself…)\n"
	.string "(And then…)\p"
	.string "(That voice…)$"

gText_Intro_YoungHuman::
	.string "Young human…\n"
	.string "Heed my call.\p"
	.string "The time is now at hand.\p"
	.string "Tell me…\n"
	.string "Do you know yourself?$"

gText_Intro_KnowMyself::
	.string "(Know myself…?)\n"
	.string "(Yes… Yes of course.)\p"
	.string "(My name is…)$"

gText_Intro_ThatsWrong::
	.string "(No, what am I saying?)\n"
	.string "(My name is…)$"

gText_Intro_ThatsWrongLeo::
	.string "(No, what am I saying?)\n"
	.string "(Her name is…)$"

gText_Intro_ThisIsYourSister::
	.string "Very well.\n"
	.string "And this one…\p"
	.string "You know her too, do you not?\p"
	.string "(That's…)\n"
	.string "(Of course I know her.)\p"
	.string "(That's my twin sister.)\n"
	.string "(Her name is…)$"

gText_Intro_TwoSouls::
	.string "{PLAYER} and {RIVAL}…\n"
	.string "Two souls, set for great things.\p"
	.string "The destiny that has been ordained\n"
	.string "for you is fast approaching.\p"
	.string "But what you do with it…\n"
	.string "Is up to you to decide.\p"
	.string "Your path… Your choices…\n"
	.string "Endless possibilities await.\p"
	.string "Now, young human…\n"
	.string "We must bid you farewell.\p"
	.string "We are looking forward to meeting you,\n"
	.string "one day.\p"
	.string "But, then again…\n"
	.string "Perhaps we already have met.\p"
	.string "$"

gText_Intro_MysteriousVoice::
	.string "Mysterious Voice"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "(Is {PLAYER}{KUN} my name…?)$"

gText_Birch_SoItsRival::
	.string "(Is {RIVAL} her name…?)$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "(Wait, no!)\n"
	.string "(Don't go yet!)\p"
	.string "(Who are you?)\n"
	.string "(And what do you mean by that?)\p"
	.string "(Answer meeee!)$"
