name: CI

on:
  push:
    branches:
      - main
      - master
      - upcoming
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      COMPARE: 0
      UNUSED_ERROR: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Install binutils
        run: |
          sudo apt update
          sudo apt install -y binutils-arm-none-eabi gcc-arm-none-eabi libnewlib-arm-none-eabi libpng-dev python3
        # build-essential and git are already installed

      - name: ROM
        env:
          COMPARE: 0
        run: make -j${nproc} -O all

      # one shall not run this step.
#      - name: Test
#        env:
#          TEST: 1
#        run: |
#          make -j${nproc} check
